server:
  port: 8190
spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgre123
  jpa:
    open-in-view: true
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      show_sql: true
      format_sql: true
  sql:
    init:
      platform: postgres
      mode: always